### ISSUE TITLE
在一个文件下载失败后该下载线程不能下载

### ISSUE THREAD

**Issue by bai0012** [xuejianxianzun/PixivFanboxDownloader#1]
下载fanbox的时候挂的梯子，网络波动的时候当前那个线程就会提示下载失败，然后那个线程就会卡住，如果三个线程都卡住的话无论怎样都不会继续下载了，点暂停再继续也不行（特别是要下几百张图片的时候，通常就会卡在100-200张左右的地方），希望能加一个对于错误文件重试的选项或者是能让线程继续使用，非常感谢。
（PS：真的非常好用，以前一张张另存为真是噩梦，感谢作者！）

**Comment by xuejianxianzun** [comment]
在设计上是应该不会卡线程的，可能是哪里出了问题。
不过排查起来有点麻烦（因为我很少下载出错，很难重现错误），所以近期不一定会修复。
这个情况首先还是建议你改善网络，比如使用更好的梯子，以及开启全局代理。
谢谢支持~

**Comment by bai0012** [comment]
感谢作者
我发现多线程确实很容易卡，然后就换成了1线程，如果下载失败了就换成2线程，这样下来就能连贯地使用了，（其实就是梯子速度有限，三个同时下就容易出错），这样操作的话就能解决了，再次感谢您！
