### ISSUE TITLE
希望在失败 - 网络错误时能自动重新下载

### ISSUE THREAD

**Issue by Arcsion** [xuejianxianzun/PixivFanboxDownloader#10]
下载时偶尔会在下载某个文件时遇到失败 - 网络错误的问题，这时整个下载队列都无法正常进行。
使用Chrome的下载内容界面，点击继续可以下载到文件；但是这样下载成功后，以及把该下载到的文件按命名格式放入目标文件夹后，下载器均无法检测到该文件已被下载，下载队列无法继续。
重新下载又会在相同的地方卡住。
源码中似乎有浏览器把文件保存到本地时出错时重新下载这个文件的功能，但这对失败 - 网络错误不起作用。
可否在遇到失败 - 网络错误时自动重新下载该文件？或是能让下载队列不至于卡住？又或者像PixivBatchDownloader那样可以导出下载链接供其他下载工具使用？

**Comment by Arcsion** [comment]
code: NETWORK_FAILED

**Comment by xuejianxianzun** [comment]
这种情况我也头疼，问题在于浏览器下载失败（通常是大文件）（甚至有时候可能下载成功了），但是下载器接收不到浏览器返回的信号，所以就卡住了。
正常情况下应该能接收到信号，但发生这种异常的时候，我也不知为何就是接收不到信号。
至于导出 url，因为 fanbox 的 url 下载时需要携带 cookie 等信息，单纯复制 url 用其他下载软件是不能下载的，所以我没添加这个功能。

**Comment by xuejianxianzun** [comment]
我在想是否可以曲线救国，添加一个“我卡了”按钮，然后点击某个进度条来跳过这个下载。
我觉得可以试试，不过也许不会马上做修改，如果做了我再回复。

**Comment by xuejianxianzun** [comment]
最新版本解决了这个问题，出错可以自动重试，你可以试试效果。
https://github.com/xuejianxianzun/PixivFanboxDownloader/releases
导出 url 不可行，因为用其他下载工具下载 rul，没有 cookie 等信息，会 403 错误。

**Comment by Arcsion** [comment]
效果很好！现在可以正常下载了，十分感谢！
