### ISSUE TITLE
不知道能不能加个 直接以网页的形式保存的功能

### ISSUE THREAD

**Issue by Riamuu** [xuejianxianzun/PixivFanboxDownloader#11]
有些画师发的主要都是文章，教程之类的，如果图片文字分开保存的话非常零碎。希望能加入保存网页的功能

**Comment by xuejianxianzun** [comment]
默认命名规则是按文章标题保存的，一篇文章里的文字和图片都在一个文件夹里，这也可以方便查看。
另外保存网页不属于下载器的功能范畴，建议使用浏览器的 Ctrl+S 自行保存，或者用长截图软件截图。

**Comment by Riamuu** [comment]
谢谢，不知道有个算不算bug，保存网页的时候，如果插件在启用状态，插件的log信息也会被保存进去

**Comment by xuejianxianzun** [comment]
这不是bug，因为log确实被输出到网页上了。
你不想要的话就在没有下载的情况下保存网页。

**Comment by Riamuu** [comment]
没下载也会保存配置的页面信息，但停用的话就不会

**Comment by xuejianxianzun** [comment]
因为下载器的界面已经被添加在页面上了，你保存网页也会保存下载器的界面，我试了下下载器界面是在底部的，问题不大。
