### ISSUE TITLE
[Enhancement] Add delay between downloads

### ISSUE THREAD

**Issue by AgileGhost** [xuejianxianzun/PixivFanboxDownloader#12]
Sorry, I don't know any other language other than English. But I think it would be a great idea to have some setting that allows you to customise a delay between downloads for people who want to go a little slower like me since I plough through them quickly and don't want to risk getting the over-usage warning. (again) Thanks for such a lovely product!

**Comment by xuejianxianzun** [comment]
What does the overuse warning mean? Is the operating system's resource usage too high?

**Comment by AgileGhost** [comment]
> What does the overuse warning mean? Is the operating system's resource usage too high?

It's where Pixiv receives too many requests in a set amount of time. It will and can suspend your account and ban your IP for a few hours, if done multiple times your account will be permanently banned along with your IP. I've received a warning before, not with this software but with another that was at similar speeds. Just want to be safe.

**Comment by xuejianxianzun** [comment]
You said that you used other software before, and I think this may not happen with this downloader.
I asked other users of this downloader and they have not encountered this situation.
This downloader is used to download Fanbox files, not Pixiv. Fanbox seems to have no download restrictions. If you encounter this limitation with this downloader, please report again.

**Comment by AgileGhost** [comment]
okay, thanks, for considering it though.
