### ISSUE TITLE
提一个bug, 设置完下载的文件名之后，再次打开新的fanbox页面，文件名规则依然为默认规则

### ISSUE THREAD

**Issue by AcoWaves** [xuejianxianzun/PixivFanboxDownloader#13]
如题，打开新的fanbox页面，命名规则变回默认的 {user}/{title}/{index}

**Comment by xuejianxianzun** [comment]
可能因为域名问题。例如 A B 两个用户，域名是 a.fanbox.cc 和  b.fanbox.cc，浏览器认为它们是不同的域名，所以你在 A 页面进行的设置只在 A 页面生效。
目前对此没有好的办法解决。

**Comment by xuejianxianzun** [comment]
3.0.0 版本解决了这个问题。
