### ISSUE TITLE
建议加入可选的更方便计算机理解的{index}的编号形式（例如01,02...或001,002...）

### ISSUE THREAD

**Issue by Eatball2** [xuejianxianzun/PixivFanboxDownloader#15]
如题，建议加入更方便计算机理解的{index}的编号形式，例如01,02,03...，或者001,002,003...010,011...这样的。因为手机相册几乎都不支持1,2,3...9,10,11这种排序。
由于fanbox一般一个post里面不会超过一百张图，所以其实适配到百位应该就可以了，比如另外制作{index00}和{index000}这两种编号形式应该就够了，不需要搞个通配啥的（不过大佬想整也可以整一个）

**Comment by xuejianxianzun** [comment]
你说计算机的理解，那要看是怎么理解，如果把编号理解为字符串，就可能导致排序错误（手机上很多软件都这样）。如果能正确理解为数字，那就不会有问题（电脑上很多软件都可以正常排序）。
这个软件的设计时在电脑上使用的，所以我不太想改。目前你可以考虑使用重命名软件批量改名 ，或者找找看能正常排序的相册软件。

**Comment by Eatball2** [comment]
可以理解，不过我个人还是认为改了的话确实会普适一些。重命名软件的话适合批量更改，但每天收图都得跑一遍重命名软件的话就太麻烦了。
我刚刚鼓捣了下源码试试，正好谷歌到了padStart这个函数，把
 '{index}': { value: data.index,
改成了
'{index}': { value: String(data.index).padStart(3, '0'),
能自娱自乐地满足我自己的需求；不过想另加一个新的{index000}格式就没那么简单了。因此对作者表示理解。
如果有考虑彻底地将index的格式更改为自动补0的形式的话，做个简单的更改就行。不过这就涉及到喜好的问题了，作者不改也ok。
若有其他和我一样需求的用户在看这条issue的话，到content.js里按如上的方法替换字段就行了（替换“data.index”为“String(data.index).padStart(3, '0')”）。
