### ISSUE TITLE
浏览器下载速度异常缓慢，希望加入调用第三方下载器的功能

### ISSUE THREAD

**Issue by Nigel-NI** [xuejianxianzun/PixivFanboxDownloader#18]
使用浏览器直接下载时的速度如图
![image](https://user-images.githubusercontent.com/23294384/139594038-6b689aa8-157a-4fe2-8a85-2f635a016835.png)
每个文件的下载速度不会超过150kb/s。以前未曾遇到类似问题，但是近几个月官方可能修改了下载策略，限制了单线程下载速度。我也尝试过更换代理等方式，但是下载速度几乎无变化。
使用第三方下载器的下载速度如图
![image](https://user-images.githubusercontent.com/23294384/139594184-8277ea4c-1884-4f56-b176-420c3cf14f41.png)
二者速度相差悬殊，但是因为赞助画师作品较多，不方便一个一个手动下载。在此恳请开发大大加入将下载任务导入aria2、idm或其他第三方下载器的选项（必要情况下可舍弃部分功能，如导入第三方下载器后若下载失败无法自动重试等）。如果可以，我想这将能节约大量下载时间。
期待开发大大回复，非常感谢！
#2

**Comment by xuejianxianzun** [comment]
下载 fanbox 的文件需要携带用户 cookie 信息，只导出 URL 是下载不了的。所以我没有做导出 URL 的功能。
你说的第三方下载软件都可以在下载时发送 cookie 吗？
我很难相信 fanbox 官方会限速的这么厉害。你用 idm 做对比的时候，下载的是同样的文件吗？
你可以尝试更新梯子的服务器列表、更换线路看是否有所改善。

**Comment by Nigel-NI** [comment]
各个地区的节点，美国、日本、新加坡、香港……都试过了，基本上都是150kb/s。我还特意用手机试了一下，同一个文件，同一个代理，浏览器速度110kb/s，用多线程下载器就可以跑到2mb/s甚至更高。
    电脑测试时也都是用同样的文件作对比。
    关于第三方下载器是否会发送cookie这档事，我也不太确定，但应该是可以做到的。
    我先是试了一下idm，有“下载”按钮的（如psd, zip等文件）可以通过复制其链接到idm完成下载，图片没试（下载成功的原因可能是因为测试前通过idm的浏览器扩展下载了文件（为了截上面那张图），idm获取到了浏览器的cookie，也不排除idm用了其他的手段）。
    而把这些链接粘贴到aria2c中下载，会提示403错误（可能是我配置不对，直接把链接粘上去就点开始了。aria2支持自定义请求头，比如用它模拟某度网盘客户端下载时的请求头
```java
User-Agent: Mozilla/5.0 (Symbian/3; Series60/5.2 NokiaN8-00/012.002; Profile/MIDP-2.1 Configuration/CLDC-1.1 ) AppleWebKit/533.4 (KHTML, like Gecko) NokiaBrowser/7.3.0 Mobile Safari/533.4 3gpp-gba

Cookie:BDUSS=XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXAAAAAAAAAAAXXXXXXXXXXXXXXXXXAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAXXXXX-XXXXXXX 
#（作者：Wuqibor https://www.bilibili.com/read/cv7494343/ 出处：bilibili）
```
）。
    我真的是走投无路了，要不然也不会有这个issue。
    前两个月也是这样，姑且忍了，但是代价太痛苦：钱已经花出去了，却没能赶在赞助到期之前将资料全部下载。
    也许其他人也有这样的困扰，我希望这种因官方限制无法拿到全部奖励的事不要再发生到别人身上。
    希望开发大大伸出援手，我这边也会力所能及地提供测试信息，感谢！

**Comment by xuejianxianzun** [comment]
我在fanbox下载器群里发了你的截图，没人反应和你有同样的问题。有3个群友说最近都是正常下载的。我们认为可能是你梯子的问题。
你可以找其他的fanbox用户交流一下。或者让别人登录你的账号下载试试，确定一下问题原因。

**Comment by wordlesswind** [comment]
> 你说的第三方下载软件都可以在下载时发送 cookie 吗？

可以，但 IDM 的公司拒绝浏览器扩展程序使用其 [API](https://www.internetdownloadmanager.com/support/idm_api.html)，理由是担心有扩展程序假冒官方扩展程序，但我不知道能否直接调用[其扩展程序](https://chrome.google.com/webstore/detail/ngpampappnmepgilojfohadhhmbhlaek)进行下载。
Aria2 支持通过 [JSON-RPC](https://aria2.github.io/manual/en/html/aria2c.html#json-rpc-over-websocket) 或 [XML-RPC](https://aria2.github.io/manual/en/html/aria2c.html#sample-xml-rpc-client-code) 对其进行调用。

**Comment by wordlesswind** [comment]
> 我不知道能否直接调用[其扩展程序](https://chrome.google.com/webstore/detail/ngpampappnmepgilojfohadhhmbhlaek)进行下载
在通过电子邮件联系了该公司后，其表示**也许**会在**下个版本**（大概是下个主要版本）中添加此特性（允许浏览器扩展程序调用其扩展程序来调用 IDM）。
