### ISSUE TITLE
命名規則失效

### ISSUE THREAD

**Issue by erslime** [xuejianxianzun/PixivFanboxDownloader#19]
在兩日前還沒有問題,但是今日不管用甚麼瀏覽器命名規則都是沒有用,我試過重新安裝/重設瀏覽器都沒有用
在預覽檔案名稱中是正常的,但下載完成是還是預設名稱(eg.ufc5U1gYP46coRDJctZBJ0vW),也不會新增資料夾
到底是fanbox更新了還是我的電腦出了問題?

**Comment by xuejianxianzun** [comment]
使用fanbox下载时，暂时禁用其他有下载管理功能的扩展。
包括 pixiv downloader。

**Comment by xuejianxianzun** [comment]
目前 Powerful Pixiv Downloader 的 11.4.2 版本会导致 fanbox 下载的文件名异常，下载 fanbox 时需要禁用它。
我已经提交了新版本，等你更新到 11.4.3 就可以解决这个问题了。
