### ISSUE TITLE
無法正確的創建資料夾以及命名

### ISSUE THREAD

**Issue by chocosaj** [xuejianxianzun/PixivFanboxDownloader#20]
不太確定是什麼問題，我用了無痕，整個瀏覽器只使用了這個擴充，抓下來的檔案依然是沒有正確的命名，也沒有創建資料夾。

**Comment by xuejianxianzun** [comment]
1. 在无痕模式中，下载器下载某些类型的文件时可能出现问题。请尝试在正常模式中使用。
2. 如果在正常模式中无法正常设置文件名，是因为其他扩展程序冲突，你可以尝试临时关闭其他扩展程序，然后刷新页面，再进行下载。（冲突的扩展程序通常是具有下载文件功能的，它们可能会修改下载器设置的文件名）

**Comment by chocosaj** [comment]
好的，應該是衝突了，剛剛直接重新創建了一個chrome的profile後，就能正常命名了。感謝
