### ISSUE TITLE
请求加入手动语言选项以及设置导出导入

### ISSUE THREAD

**Issue by aozaki-kuro** [xuejianxianzun/PixivFanboxDownloader#21]
如题
主项目Pixiv下载器可以选择语言，以及将选项导出导入，希望Fanbox版也可以做到这一点，谢谢～

**Comment by xuejianxianzun** [comment]
fanbox下载器的代码是基于早期pixiv下载器的代码，现在两者的区别已经比较大了。
把这些后来做的新功能添加到fanbox下载器上有点让我头疼。
语言的话是跟随页面语言的，选择语言的必要性很小吧。

**Comment by aozaki-kuro** [comment]
希望可以跟进版本吧，语言其实用惯日语了没有也还ok
导入导出备份还是挺重要的，需要清理cookies后设定一起被清理还是很头疼的😢

**Comment by xuejianxianzun** [comment]
我在 3.0.0 版本添加了这两个功能。
