### ISSUE TITLE
Fanbox API更新导致无法下载全部内容或者解析卡住？

### ISSUE THREAD

**Issue by BrightSphere** [xuejianxianzun/PixivFanboxDownloader#23]
这行会报错data.body undefined 
https://github.com/xuejianxianzun/PixivFanboxDownloader/blob/2b8d9a0c7fbc429a387a7f81ecf3b5db72b25151/src/ts/modules/SaveData.ts#L111
怀疑这个接口现在不返回body了
https://api.fanbox.cc/post.listCreator

这行注释掉，每个投稿就只能下载封面了

在单个投稿页面的抓取暂时还没有问题

**Comment by xuejianxianzun** [comment]
这个 api 好像确实变化了，连 data.type 都没有了。也没有返回 text

**Comment by xuejianxianzun** [comment]
这个下载器很久没修改了，很多东西我都忘了。这下麻了

**Comment by xuejianxianzun** [comment]
有些作者的作品太多的话，这样可能花的时间比较多，我先试试有没有其他办法，不行的话就这样改吧。

**Comment by xuejianxianzun** [comment]
https://github.com/xuejianxianzun/PixivFanboxDownloader/releases/tag/v1.9.0
发了新版本修复了。没办法，还是逐个抓取所有文章。
