### ISSUE TITLE
is stuck on "Task starts"

### ISSUE THREAD

**Issue by jack652** [xuejianxianzun/PixivFanboxDownloader#24]
the extension displays "Task starts" on the top of the page and does nothing
tried in opera gx and chrome

**Comment by xuejianxianzun** [comment]
Fanbox's API change caused downloader to crawl incorrectly.
Version 1.9.0 fixes this issue.
You can wait for the automatic update, or install the new version offline now.

https://github.com/xuejianxianzun/PixivFanboxDownloader/releases/tag/v1.9.0
