### ISSUE TITLE
下载过长的标题时出错

### ISSUE THREAD

**Issue by Daijin139** [xuejianxianzun/PixivFanboxDownloader#25]
执行环境
Pixiv Fanbox Downloader: v1.9.1
谷歌浏览器: 99.0.4844.82

复制程序
1. 将命名规则设置为Fanbox/{user}/{date}-{title}/{index}。
2. 保存所有被支持的用户的帖子，https://www.fanbox.cc/
3. 当保存标题很长的文章时，如果在命名规则中包含{title}标签，文件夹路径可能超过260个字符。 出现 "另存为 "窗口，即使批量下载正在进行，也会中断。 不可能再从这个状态继续前进。

修复
能否改变一下，如果标题超过一定的长度，则通过省略它来创建文件夹？

谢谢你提供了一个伟大的扩展。

**Comment by xuejianxianzun** [comment]
你把文件保存在哪里，本机上还是网络位置？

**Comment by Daijin139** [comment]
存储在网络中的一个NAS上。

**Comment by xuejianxianzun** [comment]
如果你储存到本机，Chrome会自动截断超长的文件名，但是存储到网络位置则不会。
你可以先下载到本机，然后上传到NAS。
下载器目前没有这个设置，我最近有点忙，所以近期可能也不会添加。

**Comment by Daijin139** [comment]
我们把保存位置改为本地，并确认可以保存长标题的文件夹。
文件夹名称被保存得很长，不能像以前那样从本地移到NAS，但重命名文件夹有帮助。
非常感谢你。
