### ISSUE TITLE
保存投稿資訊

### ISSUE THREAD

**Issue by JC-Chung** [xuejianxianzun/PixivFanboxDownloader#27]
投稿資訊如標題、封面網址、發文時間、價格等訊息，用json或其他格式保存。

以及對於未解鎖的付費內容，保存公開可查看的標題、封面、發文時間、價格等訊息。

謝謝

**Comment by xuejianxianzun** [comment]
目前尚无此计划。
你可以考虑修改源码并编译，下载器的内部数据保存在 ts/modules/Store.ts 的 result 数组里。你可以在抓取完成后导出它，例如：
```js
window.addEventListener(EVT.events.crawlFinish, () => {
  // export Store.result
  // ......
})
```
开发方式可以参考：https://github.com/xuejianxianzun/PixivBatchDownloader#%E5%BC%80%E5%8F%91
