### ISSUE TITLE
Download original resolution

### ISSUE THREAD

**Issue by look-at-the-sky** [xuejianxianzun/PixivFanboxDownloader#28]
Currently the extension downloads the fixed width (1200) of any post, it should download the original resolution instead.
Example (R-18): https://downloads.fanbox.cc/images/post/917/w/1200/19f38voxtq74kggwoock8swo.jpeg
VS
https://downloads.fanbox.cc/images/post/917/19f38voxtq74kggwoock8swo.jpeg
Notice the second URL is missing "w/1200/"
That's the original resolution.

**Comment by xuejianxianzun** [comment]
I tested in this post and did not find this problem:
https://www.fanbox.cc/@itsuwa0815/posts/3690430
I downloaded two files:
1. Cover
2. Original image
There is no `1200` in the URL.

**Comment by look-at-the-sky** [comment]
It happens to me when I try to download the entire fanbox of: https://nekoworks.fanbox.cc/posts
I tried all the settings, the older images should be 2508x3541 but they still get downloaded at 1200x1694 which is the resolution that is served when the URL contains "w/1200/"

**Comment by xuejianxianzun** [comment]
https://nekoworks.fanbox.cc/posts/917
Is it this one? I'm not sponsored so can't test

**Comment by look-at-the-sky** [comment]
Yes it's that one but not just that one, really all the old articles suffer the same problem.
Maybe I can send you 5 euros so you can check? I really need this to be fixed ASAP

**Comment by xuejianxianzun** [comment]
OK, you can sponsor me here:
https://www.patreon.com/xuejianxianzun

**Comment by look-at-the-sky** [comment]
Done. Check it out.

**Comment by xuejianxianzun** [comment]
Received, this problem does exist, I speculate that maybe only some early posts have this problem.

I submitted a new version, you can install it offline.

https://github.com/xuejianxianzun/PixivFanboxDownloader/releases/tag/v1.9.2

I will also submit to the extension store, but it will take time to review.

**Comment by xuejianxianzun** [comment]
Offline installation

Download the latest version of the installation package, and unzip it to a folder.

Enter the extension management. Chrome clicks "More Tools" - "Extensions Management" in the menu; Edge clicks "Extensions" in the menu.

On the extension management page, enable "Developer Mode".

Click the button "Load unpacked" and select the folder where the installation package is unzipped.

Note: After offline installation, please refresh the fanbox page or restart the browser for normal use.

**Comment by xuejianxianzun** [comment]
There are still some issues with the last version. Please change to the new version:

https://github.com/xuejianxianzun/PixivFanboxDownloader/releases/tag/v1.9.3

**Comment by xuejianxianzun** [comment]
There are still some issues with the 1.9.2 version. Please change to the new version:

https://github.com/xuejianxianzun/PixivFanboxDownloader/releases/tag/v1.9.3

**Comment by look-at-the-sky** [comment]
It seems to be working now, thank you.
PS: I hope the excessive R-18 stuff wasn't a problem for you, haha

**Comment by xuejianxianzun** [comment]
no problem.
