### ISSUE TITLE
无法下载2018-04-01之前的内容

### ISSUE THREAD

**Issue by mikage3miya** [xuejianxianzun/PixivFanboxDownloader#3]
抓取对象包含2018-04-01之前的内容时抓取会持续进行，无法结束

Fanbox在该日期进行过大规模renewal，怀疑前后的投稿结构不同导致了此现象

参考对象 しらたま https://www.fanbox.cc/@shiratamaco

**Comment by xuejianxianzun** [comment]
啊这
我头大了 去看看

**Comment by xuejianxianzun** [comment]
https://www.fanbox.cc/@shiratamaco/posts/1446
这个的类型是 entry ，第一次见，可能是早期特有的类型吧。我已经上传了1.2.1版本进行修复，你试试怎么样
https://github.com/xuejianxianzun/PixivFanboxDownloader/releases/tag/v1.2.1

**Comment by mikage3miya** [comment]
感谢跟进
1.2.1版可以对文字内容进行抓取了，有少量“&nbsp;” “&gt;” 等符号，影响不大
尚无法抓取图片内容

**Comment by xuejianxianzun** [comment]
我没赞助这个画师，你可以加群把账号发给我测试

**Comment by mikage3miya** [comment]
Pixiv账号比较敏感,恕无法提供（link了各种东西）
姑且那篇公开投稿的图片内容也抓不到……
嘛如此早期就开始的作者十分少见，不处理影响也不大就是了(ry

**Comment by xuejianxianzun** [comment]
更新了1.2.2版本，可以抓取图片，但不知道这个类型里有没有收费附件，暂且不管了。
