### ISSUE TITLE
Add an option to pad the index to a certain length

### ISSUE THREAD

**Issue by asdf1324** [xuejianxianzun/PixivFanboxDownloader#33]
There exists some applications that do not order files by the actual numeric value contained within the name (e.g. OneDrive for Android) but just by the character value. This leads to annoyances where the order becomes something like 0 - 10 - 11 - 12 - 13 - 1 - 2 - 3 - 4 ... instead of the desired 0 - 1 - 2 - 3 - 4 - ...

I suggest that we add an option to pad the index to a certain length so the length of the index stays consistent.

I see two approaches to make this happen: 
* make the length user-configurable, just like how we let users decide how to format the {date} field
  * (what should we do if we exceed the maximum length? e.g. if the user has provided 1 but the max index is actually like 20 or 101, what do we do for those 1-digit indices?)
* pad the index based on the largest index? 
  * e.g. if the largest index is 89, then we pad every number to length of 2,  if the largest index is 100, then we pad every number to length of 3....

**Comment by asdf1324** [comment]
Oops, might be a duplicate: https://github.com/xuejianxianzun/PixivFanboxDownloader/issues/15

Wondering if you still don't intend on changing this. Since I have no real other replacements for that particular application (it being a cloud storage app), finding an alternative is not an option; batch-renaming is something that I'd like to avoid as I do download a fair amount of posts frequently. Having to rename those every time I download things would be quite a hassle...

**Comment by xuejianxianzun** [comment]
I may add this feature in the future.

**Comment by xuejianxianzun** [comment]
I added this feature in version 3.0.0.

**Comment by asdf1324** [comment]
Brilliant, thanks!
