### ISSUE TITLE
[功能请求] 增加下载类型

### ISSUE THREAD

**Issue by wordlesswind** [xuejianxianzun/PixivFanboxDownloader#34]
![image](https://user-images.githubusercontent.com/9050713/178109374-2f782813-ead0-4b95-a328-13bd18ad5f15.png)
我所支持的一个画师似乎是把 pixivFanbox 当博客来用的，Ta 会在 figure 标签中放置提供的原画图像文件，而其余的图像都是博文配图。
所以希望能添加一个选项，用于只下载 figure 标签中的文件。

**Comment by xuejianxianzun** [comment]
现在是“figure 标签”里的和其余的图像都会下载吗？
感觉这种情况比较少，没有普遍性，懒得添加。

**Comment by wordlesswind** [comment]
> 现在是“figure 标签”里的和其余的图像都会下载吗？

是的，另外我注意到即便我取消勾选下载外部链接，但似乎还是会进行下载。

**Comment by xuejianxianzun** [comment]
什么样的链接呢，是不是受到保存投稿中的文字的影响了

**Comment by wordlesswind** [comment]
> 什么样的链接呢

![image](https://user-images.githubusercontent.com/9050713/178115104-2e9533c3-6e96-4bf5-baa1-4f6dcb2d60a3.png)
YouTube 外嵌播放器，我没有开启除了文件外的任何选项。

**Comment by xuejianxianzun** [comment]
这里有一个 bug，在此类有嵌入资源的文章里始终会保存外链。下个版本修复。
