### ISSUE TITLE
能否加入一个忽略错误的选项

### ISSUE THREAD

**Issue by Vector-Stack** [xuejianxianzun/PixivFanboxDownloader#38]
我这里nginx反代理大部分图片可以正常下载，但有些图片会提示错误0，然后所有图片就暂停下载了，1000多张图片就卡在200-300那样，然后就要手动点了

**Comment by Vector-Stack** [comment]
将图片下载好了以后得到错误列表，导出为抓取结果文件，之后可以翻墙下载

**Comment by xuejianxianzun** [comment]
我拒绝。

1. nginx 反代理容易出现状态码为 0 的错误，你可以换成正经的梯子。
2. 你说的在下载之后“导出错误列表，之后可以翻墙下载”是怎么个翻墙法，还是不是 nginx？如果是其他方法，那为什么不在下载时使用呢？
3. 导出的抓取结果你打算用什么软件下载？下载 fanbox.cc 的文件时必须发送你的 cookie，否则就无法下载这些文件。
