### ISSUE TITLE
支持根据稿件标题来排除部分稿件

### ISSUE THREAD

**Issue by neko-para** [xuejianxianzun/PixivFanboxDownloader#40]
部分作者的源文件也是压缩包，无法通过文件类型来区分排除

**Comment by neko-para** [comment]
另外能不能默认就把不下载重复文件打开（或者说清楚点，第一眼还以为是不下载内容相同的文件，结果是不下载下载过的文件）？我tm下了20G之后卡死了重下，发现下了一堆(1)的，就把原来的删了，然后才看到这个选项

**Comment by xuejianxianzun** [comment]
就是不下载内容相同的文件啊。

**Comment by xuejianxianzun** [comment]
你下载过的，再次下载时，如果URL相同，就不再下载。哪里有问题？
这个功能是不适合默认打开的，因为它只能依靠下载器自己的下载记录，而不是检测硬盘上的文件，所以不是完全准确的。

**Comment by neko-para** [comment]
但是正常的逻辑难道不就是：我知道我下过了，所以我默认不下、用户告诉我需要下载下过的我才下载吗

**Comment by neko-para** [comment]
主要是，我认为这个选项的描述不是很精确，“跳过已下载的文件”是否更好？跳过应该能更好的阐释这个选项的用途吧

**Comment by neko-para** [comment]
“重复的文件”和“已下载的文件”语义并不是一致的，我hover才能看到提示，才知道说的是这个意思、、、

**Comment by xuejianxianzun** [comment]
你之前的理解是什么样的呢，是觉得其他途径保存的文件，下载器也能识别并跳过下载？

**Comment by neko-para** [comment]
> 你之前的理解是什么样的呢，是觉得其他途径保存的文件，下载器也能识别并跳过下载？

并不是，我的理解是，字面意思就是：不下载重复文件，或者说内容一致的文件。我当时确实觉得这个功能有些奇怪，但是也并不是很突兀。现在想想倒是因为读不了下载的内容也判定不了

**Comment by xuejianxianzun** [comment]
我已经说了，这个功能并不准确，即使用户把下载到一半的文件删了，下载器也不会知道。
如果默认开启这个设置，那么第二次下载时就只会下载后一半的文件了。这样又会有用户来找我麻烦。所以这个设置不能默认开启。

**Comment by xuejianxianzun** [comment]
> > 你之前的理解是什么样的呢，是觉得其他途径保存的文件，下载器也能识别并跳过下载？
> 
> 并不是，我的理解是，字面意思就是：不下载重复文件，或者说内容一致的文件。我当时确实觉得这个功能有些奇怪，但是也并不是很突兀。现在想想倒是因为读不了下载的内容也判定不了

下载器是依据URL判断是否重复的啊，URL一样的就是内容一样的，有什么区别。

**Comment by xuejianxianzun** [comment]
如果作者把一个文件修改后重新上传，那么URL就变了，下载器不会认为它是下载过的。

**Comment by neko-para** [comment]
是，默认到底开不开都行了，主要还是觉得，这个“重复的文件”在理解上要转个弯，当时想找跳过已下载过的文件的选项时真没想到是这个选项

**Comment by neko-para** [comment]
哎主要是白下了20多个G，然后现在网络又炸了只有几十k的速度，人麻了、、、
---
主要还是想看看能不能加一个根据标题排除投稿的功能、、、

**Comment by neko-para** [comment]
哎主要是白下了20多个G，然后现在网络又炸了只有几十k的速度，人麻了、、、
---
主要还是想看看能不能加一个根据标题排除投稿的功能、、、

**Comment by neko-para** [comment]
另外就是，不知道为什么，下载似乎不是准确的按照发布顺序在下载，我当时考虑根据时间来筛选重新下载后面的部分，结果看下来正在下载（被我暂停掉了）的投稿超过20（下载了的前面有完全没下的，这种感觉），找不到一个分界线

**Comment by xuejianxianzun** [comment]
因为下载时多个下载进度并不是按顺序完成的，可能后下载的文件先完成，所以下载顺序会变得无法保持时间顺序。
如果你需要依赖时间，应该是用 {date}  标记。

**Comment by neko-para** [comment]
> 因为下载时多个下载进度并不是按顺序完成的，可能后下载的文件先完成，所以下载顺序会变得无法保持时间顺序。 如果你需要依赖时间，应该是用 {date} 标记。

行吧，所以不同子进程的下载任务是提前分配的，而不是下载完成后从全局列表中提取的咯，行吧

**Comment by xuejianxianzun** [comment]
我说的不准确，下载顺序会按照时间顺序，但是文件下载完成时的时间是另一个时间，并不是说先下载的文件就会先完成。
所以我让你使用 {date} 标记。

**Comment by xuejianxianzun** [comment]
天天当客服好累啊。标题排除的功能以后更新加上吧。

**Comment by neko-para** [comment]
诶，但是我已经是用${post}了来排序了，最小的按理说就是最早发布的（也就是最新下载），但是实际上那并没有连上，中间有不少post都没下，所以我才怀疑下载顺序不是按照post的日期来（或者说，不完全是）

**Comment by xuejianxianzun** [comment]
确实有这个可能，抓取投稿信息时是并发多个网络请求的，由于每个网络请求的时间不会完全一致，所以后发送的请求可能先返回数据。这也会造成数据顺序乱掉。

**Comment by xuejianxianzun** [comment]
3.2.0 版本增加了标题筛选的功能，并且会按照文章id（发布时间）下载作品。
