### ISSUE TITLE
4.0.0版本未登录的时候访问作者fanbox主页报error

### ISSUE THREAD

**Issue by EricHongXDD** [xuejianxianzun/PixivFanboxDownloader#43]
环境：Chrome 108.0.5359.125
未登录时访问链接：https://rurudot.fanbox.cc/
报错：
Access to XMLHttpRequest at 'https://api.fanbox.cc/tag.getFeatured?creatorId=rurudot' from origin 'https://rurudot.fanbox.cc' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header has a value 'https://www.fanbox.cc' that is not equal to the supplied origin.
api.fanbox.cc/tag.getFeatured?creatorId=rurudot:1          Failed to load resource: net::ERR_FAILED
rurudot.fanbox.cc/:1 Access to XMLHttpRequest at 'https://api.fanbox.cc/plan.listCreator?creatorId=rurudot' from origin 'https://rurudot.fanbox.cc' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header has a value 'https://www.fanbox.cc' that is not equal to the supplied origin.
api.fanbox.cc/plan.listCreator?creatorId=rurudot:1          Failed to load resource: net::ERR_FAILED
rurudot.fanbox.cc/:1 Access to XMLHttpRequest at 'https://api.fanbox.cc/creator.get?creatorId=rurudot' from origin 'https://rurudot.fanbox.cc' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header has a value 'https://www.fanbox.cc' that is not equal to the supplied origin.
api.fanbox.cc/creator.get?creatorId=rurudot:1          Failed to load resource: net::ERR_FAILED
fanbox.bd3379f34a163fdd615e.js:54 Uncaught (in promise) Error: Network Error
    at t.exports (fanbox.bd3379f34a163fdd615e.js:54:138035)
    at f.onerror (fanbox.bd3379f34a163fdd615e.js:54:137000)
    at XMLHttpRequest.r (fanbox.bd3379f34a163fdd615e.js:141:25194)
![QQ图片20221225170915](https://user-images.githubusercontent.com/28833366/209462500-3a29d74d-19d4-4686-96ff-f9ef47bddbe6.png)

**Comment by xuejianxianzun** [comment]
下次更新修复。
