### ISSUE TITLE
儲存規則可否依照附檔名訂製？

### ISSUE THREAD

**Issue by GornBear** [xuejianxianzun/PixivFanboxDownloader#44]
許多繪師會替壓縮檔/影片/pdf/psd檔案命名，但圖片名稱常常是隨機編碼
因此習慣在儲存zip等壓縮檔會使用{name}
但儲存png/jpg圖片時會使用{index}
想請問有無方法可以只在儲存圖片時使用{index}，其他檔案使用{name}？
或可否更新類似功能？

**Comment by xuejianxianzun** [comment]
我打算在之后添加这项功能，到时候把图片文件和非图片文件的命名规则分开设置。
这样可以让图片使用 {index}，其他文件使用 {name}。

**Comment by xuejianxianzun** [comment]
4.2.0 版本已提交审核，添加了此功能。
