### ISSUE TITLE
4.2.0设置起始日期无效

### ISSUE THREAD

**Issue by hongsongshu** [xuejianxianzun/PixivFanboxDownloader#45]
4.2.0设置起始日期无效 设置起始日期他还是从头开始下载 刷新页面后其实日期被清零

**Comment by xuejianxianzun** [comment]
我试了没有问题。
https://www.fanbox.cc/@xuejianxianzun
设置从 2023 年抓取，只有一篇文章，两个文件，是正常的。
![image](https://user-images.githubusercontent.com/17283977/229332760-5c1c88de-a4d5-4cdd-8ed7-048443eeea74.png)

至于日期被清零的问题我并不能确定，你可以刷新页面后重新设置一次。

**Comment by hongsongshu** [comment]
嗯,如果直接设置日期立刻下载就会全部下载,以前是改完日期刷新后再下载日期限制才生效,现在有时候刷新后刚设置的日期会没了,能否改日期那里加个确定按键.

xuejianxianzun ***@***.***> 于2023年4月2日周日 14:15写道：

**Comment by xuejianxianzun** [comment]
投稿时间设置需要在抓取之前设定好，而不是能够“立刻下载”时。
