### ISSUE TITLE
图片命名无效

### ISSUE THREAD

**Issue by Reinforce-brs** [xuejianxianzun/PixivFanboxDownloader#47]
![image](https://user-images.githubusercontent.com/56968656/235331173-a4b9640c-353a-4a3f-ba0a-142ebf7c4727.png)
![image](https://user-images.githubusercontent.com/56968656/235331176-0124947a-caaa-421b-883d-6d3153fe98a8.png)
为什么图片命名规则无效了，明明预览文件名也没问题，一下载就变成不知道什么的ID了

**Comment by xuejianxianzun** [comment]
为什么不先查看常见问题呢？

**Comment by Reinforce-brs** [comment]
> 为什么不先查看常见问题呢？

我没有其他的下载插件了啊，而且以前的文件名是正常的，最近才开始奇怪

**Comment by xuejianxianzun** [comment]
其他插件都关了试试。尤其是名字里带 downloader 的，比如patreon 的。

**Comment by Reinforce-brs** [comment]
> 其他插件都关了试试。尤其是名字里带 downloader 的，比如patreon 的。

噢噢，好了，谢谢大佬。全关了就可以了0 0
