### ISSUE TITLE
?

### ISSUE THREAD

**Issue by AyushNX** [xuejianxianzun/PixivFanboxDownloader#48]
why this not downloading the premium content of pixiv fanbox, it just download the thumbnails!

**Comment by xuejianxianzun** [comment]
？
Do you sponsor artists? If he has paid content, you have to sponsor him first.
Downloaders cannot bypass paid restrictions.

**Comment by AyushNX** [comment]
> ？ Do you sponsor artists? If he has paid content, you have to sponsor him first. Downloaders cannot bypass paid restrictions.

no i'm not sponsor artists!

**Comment by xuejianxianzun** [comment]
haha

**Comment by AyushNX** [comment]
then what downloader for?
