### ISSUE TITLE
when saving a too large list, use a text file instead of HTML code or name the file .html

### ISSUE THREAD

**Issue by LolLord-xT** [xuejianxianzun/PixivFanboxDownloader#49]
a .txt with html code is a pain to read to be honest

**Comment by xuejianxianzun** [comment]
What list?

**Comment by LolLord-xT** [comment]
the file list, when you click preview file name and that list gets too long

**Comment by xuejianxianzun** [comment]
This issue has been confirmed and I have submitted version 4.2.3 to fix it.
