### ISSUE TITLE
An error

### ISSUE THREAD

**Issue by helos1020** [xuejianxianzun/PixivFanboxDownloader#5]
『Crawl finished but did not find files that match the filter criteria』

![556456](https://user-images.githubusercontent.com/73202872/96653812-82901680-1329-11eb-9fdf-01db799e1eb7.jpg)

Why do this warning appear? What is the solution?
Please let me know.

**Comment by xuejianxianzun** [comment]
No file to download was found. It may be due to the following reasons:
Did you sponsor this painter?
Can you download this resource for your sponsorship amount?
Are the filter conditions set inappropriate?
Please check or modify the filter conditions..
