### ISSUE TITLE
请求添加 aria2 rpc 支持

### ISSUE THREAD

**Issue by WallBreakerNO4** [xuejianxianzun/PixivFanboxDownloader#50]
如题，请求添加通过rpc将下载推送至aria2服务端的支持

**Comment by xuejianxianzun** [comment]
我没有计划添加 aria2 支持。

有一些原因：
1. 我并未使用 aria2。
2. 发送到 aria2 之后，下载器可能或许无法知道下载是否成功，以及何时完成。这使得错误重试以及显示下载进度的功能难以实现。
3. 某些功能生成的 txt 文件是动态生成的，没有可供 aria2 使用的网络 URL。（例如：保存投稿中的外部链接，保存投稿中的文字 ）
