### ISSUE TITLE
A post becomes Code: SERVER_FAILED

### ISSUE THREAD

**Issue by Rsfinder** [xuejianxianzun/PixivFanboxDownloader#51]
Hi.
I recently started using pixiv Fanbox Downloader. It has been very helpful. Thanks for creating a great tool.

I save all the posts of each author's account at once (no subscription) and later find good posts and buy them.
In the process, I found an error when I saved for one account.
https://www.fanbox.cc/@chisamell

Here it is
`https://pixiv.pximg.net/c/1200x630_90_a2_g5/fanbox/public/images/post/4368124/cover/0ifP7kowU3zvjwFX2fPCze4c.jpeg Download error! Code: SERVER_FAILED. Will try again later.`
The above error occurs and saving stops.

Do you know the cause? It is not a big problem and I would be happy to get it solved if there is enough time.

I will continue to support you. Hope it continues to be a good tool.

**Comment by xuejianxianzun** [comment]
First of all thank you for your support.
SERVER_FAILED is a server-side error. Judging from the URL, it may be that the cover image in this post failed to download:
https://www.fanbox.cc/@chisamell/posts/4368124
When I open this post, I see the error in the console:
```
Failed to load resource: the server responded with a status of 500 ()
0ifP7kowU3zvjwFX2fPCze4c.jpeg:1
```
So this is a server-side error, not a downloader bug.
![image](https://github.com/xuejianxianzun/PixivFanboxDownloader/assets/17283977/13051235-5e03-4665-9af1-7b0c3729d002)

**Comment by xuejianxianzun** [comment]
For this kind of problem, the downloader will try to download the thumbnail of the image. However, since the cover image does not have a thumbnail, the downloader can only try again using the original URL, so the download has never been completed.
In the future, I will optimize related prompts and avoid infinite retries.

**Comment by xuejianxianzun** [comment]
The next update will change the prompt to this:
```
https://pixiv.pximg.net/c/1200x630_90_a2_g5/fanbox/public/images/post/4368124/cover/0ifP7kowU3zvjwFX2fPCze4c.jpeg Download error! Code: SERVER_FAILED. This is a server-side error, not a downloader bug. The downloader will retry the download.
https://pixiv.pximg.net/c/1200x630_90_a2_g5/fanbox/public/images/post/4368124/cover/0ifP7kowU3zvjwFX2fPCze4c.jpeg Unable to retry, this file has been skipped.
```

**Comment by Rsfinder** [comment]
Thanks for responding!
I tried again with the URL where the problem occurred and was able to skip it and save the rest.
Thank you for the help, there are other pixiv/pixivfanbox saving tools out there, but yours is probably the only one that works as well as this.

I will report any other problems.
Thanks for a great tool!
