### ISSUE TITLE
Images and Files are not downloading

### ISSUE THREAD

**Issue by Aergernis** [xuejianxianzun/PixivFanboxDownloader#52]
Hi,

today download of files and images stopped downloading. Only Text is downloading.

Edge: 117.0.2045.36 64-Bit
Downloader: 4.2.4

`js/content.js:7591 (request.onerror)

                this.db = request.result;
                resolve(request.result);
            };
            request.onerror = (ev) => {
                console.error('open indexDB failed');
                console.trace();
                reject(ev);`

`js/content.js:4698 (Anonyme Funktion)

            if (!db.objectStoreNames.contains(this.storeName)) {
                const store = db.createObjectStore(this.storeName, { keyPath: 'url' });
                store.createIndex('url', 'url', { unique: true });
            }
        };
        return new Promise(async (resolve, reject) => {
            resolve(await this.IDB.open(this.DBName, this.DBVer, onUpdate));
        });
    }`

`js/content.js:4772 (Anonyme Funktion)

            // 如果未启用去重，直接返回不重复
            if (!_setting_Settings__WEBPACK_IMPORTED_MODULE_3__["settings"].deduplication) {
                return resolve(false);
            }
            // 在数据库进行查找
            const data = (await this.IDB.get(this.storeName, this.removeHttp(result.url)));
            return resolve(!!data);`

**Comment by xuejianxianzun** [comment]
我测试了可以下载。

**Comment by Aergernis** [comment]
Hi,
allready tried to restart Brwoser without luck. Also resetting allready downloaded don't work. I gues it's not resetting.

**Comment by xuejianxianzun** [comment]
You can try clearing your browser cache of images and files. Ctrl+shift+Del

**Comment by Aergernis** [comment]
clearing cache and files didn't work. I'll try to clean edge completly from system and reinstall when i've time on weekend and report back.

**Comment by Aergernis** [comment]
So, after some testing it seams to be a problem with a patch from https://github.com/Ceiridge/Chrome-Developer-Mode-Extension-Warning-Patcher and "Remove send to self" Patch is selected

**Comment by xuejianxianzun** [comment]
I am not sure as well.

**Comment by Aergernis** [comment]
Maybe i should open a issue ther too? Maybe they can fix it or point to the problem.

**Comment by xuejianxianzun** [comment]
I have no idea.
