### ISSUE TITLE
在特定画师页面中，下载进度条中最后一两个文件无法完成

### ISSUE THREAD

**Issue by SIPHON2936** [xuejianxianzun/PixivFanboxDownloader#53]
https://www.fanbox.cc/@yorunogumo 页面中（赞助1000日元档），下载进度条最后会有一两个文件一直卡在0%进度，导致下载一直无法完成。但实际上所有文件已经下载完成了，只是进度条没有动，刷新页面或暂停开始后进度条恢复正常，但会导致那一两个文件被重复下载。测试了brave 1.58.131和edge 117.0.2045.36、重置过扩展设置，均出现相同问题。在其他画师页面中暂未发现此问题。

**Comment by SIPHON2936** [comment]
在另一画师页面https://www.fanbox.cc/@signalviolet  也出现相同问题，可能文件达到一定数量就会触发？到最后会报错：
https://downloads.fanbox.cc/images/post/4519076/M3DPtfjSOLt6yFSSMLLdmjMZ.jpeg Download error! Code: SERVER_FAILED. Will try again later.
668 / 670
但实际上所有文件已经下载完成了

**Comment by xuejianxianzun** [comment]
SERVER_FAILED 是服务器端错误，或者和代理有关？我没什么头绪。

**Comment by xuejianxianzun** [comment]
你看看另一个issues：
https://github.com/xuejianxianzun/PixivFanboxDownloader/issues/51

**Comment by xuejianxianzun** [comment]
你说的“668 / 670 但实际上所有文件已经下载完成了”，这是因为下载器对 SERVER_FAILED 的文件会重试，尝试下载其缩略图。
有的重试能成功，所以文件数量是对的。有的不能成功，就会一直卡住。

**Comment by SIPHON2936** [comment]
但是在第一个页面https://www.fanbox.cc/@yorunogumo 中，并没有出现任何报错信息，最后只是停留在589 / 590或588 / 590。并且我重复尝试了10余次，都能稳定复现，每次卡住的文件都不相同且数量稳定在1-2个。通过对比文件数量和大小可以确定每一次实际上都已经下载完成，个人认为很难用服务器错误来解释

**Comment by xuejianxianzun** [comment]
我没法尝试，要不你把你的账号发给我，我再下载试试？
