### ISSUE TITLE
请求添加打包成压缩包下载的支持

### ISSUE THREAD

**Issue by PianCat** [xuejianxianzun/PixivFanboxDownloader#57]
如题，有一个早期的脚本（现在已失效）
采用的是获取后打包成压缩包的形式，分大小打包，然后供用户下载那样的操作模式

**Comment by xuejianxianzun** [comment]
我没有计划支持zip打包。zip打包会使用较多的内存和 cpu 资源，而且下载之后不还是要解压出来吗。
