### ISSUE TITLE
Note regarding the official statement from Fanbox

### ISSUE THREAD

**Issue by asdf1324** [xuejianxianzun/PixivFanboxDownloader#58]
They have added a new rule in the terms of service: https://www.fanbox.cc/@official/posts/6999106

> In addition, as a "prohibited act under the pixiv FANBOX Guidelines", we prohibit the collection of content by the program.
> 
> ・Acts of collecting content using programs such as crawlers
> 
> If we detect these acts, we will take measures including suspension of the account.
> 
> For some time, we have received many inquiries about unauthorized reproduction of content published on FANBOX on certain websites.
> 
> Since the website was crawled using the program and engaged in large-scale unauthorized reprinting, we took action against accounts that appeared to be complicit in the unauthorized reproduction in September 2023 based on the above terms.
> 
> In the future, as soon as we detect unauthorized reproduction and crawling of content, we may take measures such as suspending your account without notice.
> 
> In addition, please note that if the Company or a third party suffers damage due to a violation of the Terms of Use, we may claim damages.

Since they are prohibiting the use of crawlers, should we perhaps consider adding some sort of throttling mechanism and / or consider adding notes regarding No. of concurrent threads to prevent getting banned?

I think we'll have to see how it goes for now, as the notice just came out.

**Comment by xuejianxianzun** [comment]
At present, this policy has no impact on downloader users. It might be for large-scale crawling (e.g. using multiple accounts on the same IP for downloading).
