### ISSUE TITLE
命名规则不通用

### ISSUE THREAD

**Issue by zhaomma** [xuejianxianzun/PixivFanboxDownloader#6]
非三W开头，用户名前置的网址会显示不同规则。
www.fanbox.cc/@xxxx
xxxx.fanbox.cc

**Comment by xuejianxianzun** [comment]
xxxx.fanbox.cc
这种能给个url吗，我现在找不到这种用户

**Comment by xuejianxianzun** [comment]
因为对于第二种网址，每个用户名是不同的，每个用户的网址之间都是跨域的。
在 `www.fanbox.cc/@xxxx` 里保存的 localStorage  数据在 `xxxx.fanbox.cc` 里获取不到。
在 `aaa.fanbox.cc` 里保存的数据在 `bbb.fanbox.cc` 也获取不到。
所以会出现你说的情况。
如果你以  `xxxx.fanbox.cc` 方式访问，则每个用户都必须单独设置一遍规则。

所以请始终以第一种网址形式访问。fanbox 官方也是使用这种。
