### ISSUE TITLE
booth api

### ISSUE THREAD

**Issue by thisoverride** [xuejianxianzun/PixivFanboxDownloader#61]
嗨，我目前正在开发一个基于 Booth 网站抓取的 API，以获取尽可能多的（免费）数据。我想知道是否存在一个已经可以执行这项任务的 Booth API？因为在长时间的搜索中，我并没有找到相关的信息。我注意到您好像使用了一个 Booth API 的链接，对吗？

**Comment by decoratorflow** [comment]
好的，谢谢。您知道 Booth 是否有相应的 API 吗？

**Comment by xuejianxianzun** [comment]
我不清楚，没研究过
