### ISSUE TITLE
【bug?】chrome浏览器不显示下载界面了  

### ISSUE THREAD

**Issue by ElaineOwO** [xuejianxianzun/PixivFanboxDownloader#64]
chrome浏览器不显示下载界面了    右键插件有一条显示"无法读取或更改网站数据“

**Comment by xuejianxianzun** [comment]
你是否是在 https://www.fanbox.cc/ 网站里操作的？

**Comment by ElaineOwO** [comment]
> 你是否是在 https://www.fanbox.cc/ 网站里操作的？

是在pixiv

**Comment by ElaineOwO** [comment]
> 你是否是在 https://www.fanbox.cc/ 网站里操作的？

啊  好像pixiv的下载器不见了，，~我是笨蛋~

**Comment by ElaineOwO** [comment]
> > 你是否是在 https://www.fanbox.cc/ 网站里操作的？
> 
> 啊 好像pixiv的下载器不见了，，~我是笨蛋~
