### ISSUE TITLE
Would it be possible to include the download history in the Export Settings?

### ISSUE THREAD

**Issue by Rsfinder** [xuejianxianzun/PixivFanboxDownloader#65]
(apologies if this setting is already available)

Thanks again for continuing to provide FANBOX Downloader.
I want to switch from my current browser to another one, 
is it possible to include my download history in my current Export Settings?

if you are using a cache or cookie that would be difficult, but if it is recorded in an add-on I would like to see it included

but this is not an important feature or anything, so it would be nice if it could be done. there would be no demand for it😐

**Comment by xuejianxianzun** [comment]
![image](https://github.com/xuejianxianzun/PixivFanboxDownloader/assets/17283977/a3045fee-4d88-4f82-bfd9-06ede0a860fb)
