### ISSUE TITLE
可以增加设置价格范围的功能吗？

### ISSUE THREAD

**Issue by DaemonWalker** [xuejianxianzun/PixivFanboxDownloader#66]
RT，现在只能设置一个最小值，可以变成一个区间吗？
有的画师针对于不同的赞助范围，作品质量差别很大，所以想通过这个功能进行一下分类

**Comment by xuejianxianzun** [comment]
目前还没有计划。你说的情况通常是赞助金额越高，作品质量越高吧，这样只需要增加最小值就可以。
必须中间值的情况还是挺少的。

**Comment by xuejianxianzun** [comment]
下一次更新会添加等于某个价格的功能。
如果你想要个区间，那么通常一个作者只有少数几个赞助价格，你分别设置为 = 某个价格，分几次抓取也可以。
