### ISSUE TITLE
请问一下，有什么方法能实现Windows下订阅自动化吗

### ISSUE THREAD

**Issue by w211691** [xuejianxianzun/PixivFanboxDownloader#67]
比如，我Fanbox订阅了几位作者，作者更新后能自动进入页面下载，并按照名称把文件夹移动到指定位置。如果有压缩包则按照指定格式自动解压。试了一下Power Automate，筛选到订阅邮件后不会自动转跳到对应页面。。。不知道大佬们有什么好办法吗

**Comment by xuejianxianzun** [comment]
我不知道
这应该需要一个单独、独立的的应用程序，而不是浏览器扩展来做。

**Comment by w211691** [comment]
> 我不知道 这应该需要一个单独、独立的的应用程序，而不是浏览器扩展来做。

好的谢谢，我的确是打算用其他程序做，只不过目前没有思路。。。
