### ISSUE TITLE
Automatic "Like" after download

### ISSUE THREAD

**Issue by Rsfinder** [xuejianxianzun/PixivFanboxDownloader#68]
(This is not a convenience feature of the tool)

I mark "Like" after each download to make it easier to visually identify if the file has been saved or not.
in addition, it is meant to convey a message of support to the contributor.

the biggest loss to the tool and to ourselves would be if the contributors' fanboxes were shut down. 
if they deem the fanbox worthless and post on other sites, it will be harder to check.

wouldn't it be nice if the users of this tool downloaded and "liked" the postings at the same time, sending a message to the contributors that there are a lot of people out there who are interested in their postings?

please consider this🙏

**Comment by xuejianxianzun** [comment]
What you said makes sense, but I haven't decided whether to implement this feature. Maybe later?

**Comment by Rsfinder** [comment]
can be low priority
my assumption is that it would be nice to be able to add a like when saving a single post.
If we add a like when you save all posts, it will look like a bot. 
that would be risky
