### ISSUE TITLE
希望允许“图片的命名规则”可以为绝对路径

### ISSUE THREAD

**Issue by continue-revolution** [xuejianxianzun/PixivFanboxDownloader#69]
您好，首先感谢您的工具，非常有用。

我的浏览器始终会在`~/下载`目录下建立子目录，我的需求是使用绝对路径保存文件，以便将文件保存到机械硬盘，并避免下载重复文件。然而我发现您的浏览器插件会自动去除`/home/xxx`的第一个`/`，我希望不要去除。

如果您不愿意添加此功能，麻烦告知您将首个`/`去掉的代码在哪里，我可以自行去除。

**Comment by xuejianxianzun** [comment]
你是否有看到过下载器的说明：
>下载的文件保存在浏览器的下载目录里。
这是浏览器的规定。所以你那个 `/home/xxx` 是另一个目录吗？这是无效的。

另外下载器向浏览器传递下载请求时，无法使用绝对路径，也无法使用相对路径，只能使用普通字符开头的路径。浏览器会自动处理为相对于浏览器下载目录的子路径。

下载器的确会去掉开头的 `/`，否则浏览器会报错“无效的文件名”，并拒绝下载。

代码在这路：
https://github.com/xuejianxianzun/PixivFanboxDownloader/blob/3c956bf6d12adfec28108387cfc3a81da8142b6c/src/ts/FileName.ts#L160
