### ISSUE TITLE
Naming Error?

### ISSUE THREAD

**Issue by NoName10010** [xuejianxianzun/PixivFanboxDownloader#7]
Hello!

When same name and different extensions files are saved,
some files' names are added "0+random number".
e.g.) foo.jpg, foo.psd -> foo.jpg, foo0.df58f2.psd

Is this specification? or error?

**Comment by xuejianxianzun** [comment]
This is a special treatment, but it is worse.
Version 1.5.0 has been optimized, so you don't need to worry about this problem.
https://github.com/xuejianxianzun/PixivFanboxDownloader/releases
The app store will need to be reviewed for some time.
