### ISSUE TITLE
下载中会突然卡住。。

### ISSUE THREAD

**Issue by 869044974** [xuejianxianzun/PixivFanboxDownloader#8]
尝试暂停再开始还是没有反应，不知道是什么问题。

**Comment by xuejianxianzun** [comment]
目前会有这种情况，你可以升级到最新版本 1.6.0 ，对这个情况有所改善，但不能彻底解决。
导致这个问题的原因通常是网络问题。一旦卡住，暂停开始确实没有反应，需要停止再开始，也就是重新下载。

**Comment by xuejianxianzun** [comment]
最新版本解决了这个问题，出错可以自动重试，你可以试试效果。不需要手动暂停，让下载器自动重试即可。
https://github.com/xuejianxianzun/PixivFanboxDownloader/releases
